# GitHub Advanced Security - Custom Secret Scanning Patterns (Demo)
# 官方文件：https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning
# 說明：這些規則用於 DEMO，皆為假資料格式，請勿放真正憑證。
# 新增或修改後，GitHub 後端需要數分鐘到數十分鐘才會開始套用新規則。

secret-scanning:
  custom-patterns:
    # 1) 內部 Demo Token：INT-DEMO- 開頭 + 10 以上大寫或數字
    - name: Internal Demo Token
      regex: '(?<secret>INT-DEMO-[A-Z0-9]{10,})'
      # secret-group 指向上方 named group；若不用 named group 也可用整個模式 (0)
      secret-group: secret
      # 可選：限制掃描路徑 (不設代表全 repo)
      # paths:
      #   include:
      #     - '**/*.txt'
      #   exclude:
      #     - 'docs/generated/**'
      # 建議：Demo 用不需要 allowlist；若要排除誤報可用 paths.exclude

    # 2) 假 OpenAI API Key：sk- 開頭，後接 20~48 長度 (字母數字或 -_)
    - name: Fake OpenAI Key (Demo)
      regex: '(?<secret>sk-[A-Za-z0-9_-]{20,48})'
      secret-group: secret
      # 可能產生誤報，實務上可再加前綴限定，例如 OPENAI_API_KEY=sk-...

    # 3) 假 GitHub PAT：ghp_ 後接 36 位英數
    - name: Fake GitHub PAT (Demo)
      regex: '(?<secret>ghp_[A-Za-z0-9]{36})'
      secret-group: secret

    # 4) Slack Webhook URL：hooks.slack.com/services/Txxx/Bxxx/xxx
    - name: Slack Webhook URL (Demo)
      regex: '(?<secret>https://hooks\.slack\.com/services/[A-Z0-9]{8,}/[A-Z0-9]{8,}/[A-Za-z0-9]{16,})'
      secret-group: secret

    # 5) Azure Storage Connection String (簡化偵測：AccountName= + AccountKey= Base64)
    - name: Azure Storage Connection String (Demo)
      regex: '(?<secret>DefaultEndpointsProtocol=https;AccountName=[a-z0-9]{3,24};AccountKey=[A-Za-z0-9+/]{40,}=;EndpointSuffix=core\.windows\.net)'
      secret-group: secret

    # 6) Fake JWT (三段 base64url, 粗略偵測) - 可能誤報，僅示範
    - name: JWT Token (Demo)
      regex: '(?<secret>ey[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,})'
      secret-group: secret
      # 若誤報太多，可加前綴如 JWT= 或 Bearer\s

    # 7) 假 RSA 私鑰標頭 (截斷) - 用於提醒不要提交私鑰
    - name: Private Key Block (Demo)
      regex: '-----BEGIN (?:RSA |EC |)PRIVATE KEY-----'
      secret-group: 0

  # 如需忽略已知假值，可使用 allowlist (針對特定值或路徑)
  # allowlist:
  #   secrets:
  #     - INT-DEMO-IGNORE-THIS-EXAMPLE
  #   paths:
  #     - 'docs/examples/**'
  #   regexes:
  #     - 'sk-DO_NOT_FLAG_THIS_DEMO'

# 使用建議：
# 1. 建立新 branch，提交本檔與假秘密檔案 (如 demo_exposed_secrets.txt)。
# 2. 發 PR 後等待掃描觸發 (數分鐘)。
# 3. 前往 Security > Secret Scanning > Alerts 查看結果。
# 4. Demo 結束可：a) 關閉 Alerts；b) 刪除檔案；c) 修改規則減少誤報。
